"""The geometry a country needs, derived from geometry the site already has.

    python3 tools/tourism/build.py geo --check
    python3 tools/tourism/build.py geo

Three of the four things in tourism/neighbours.json and tourism/shapes.json are
derivable, and deriving them is the difference between adding a country in an
afternoon and adding one in a week:

  shapes    the outline behind an unresolved slot. tourism/map.json already
            holds every African country's path in continent coordinates — the
            twenty on the map and the thirty-three drawn as the rest of it — so
            a plate outline is that path moved to the origin and scaled to a
            1000-wide box. Checked against the twenty-two already written by
            hand: same shape to within half a unit in a thousand.
  km        every country's distance to every other. Great-circle from the
            centres, which is arithmetic, and it was a 22x22 table maintained
            by hand.
  borders   NOT derived. Two outlines touching on a simplified map is not a
            land border — Lesotho is inside South Africa, the Gambia is inside
            Senegal, and at this simplification Equatorial Guinea's mainland
            touches things it does not border. So borders stay authored, and
            what this does instead is refuse to let them be wrong: every border
            has to be mutual, and has to name a country the atlas actually has.

centres are authored too. A centroid of a simplified outline is not where a
country's middle is, and these are used for "how far is it from here".
"""

import json
import math
import os
import re

from .model import ROOT, load_countries

MAP = os.path.join(ROOT, "tourism", "map.json")
SHAPES = os.path.join(ROOT, "tourism", "shapes.json")
NEIGHBOURS = os.path.join(ROOT, "tourism", "neighbours.json")
BOX = 1000.0                   # the width every plate outline is scaled to

# The map draws the rest of the continent under Natural Earth's names. These are
# the ones that differ from the slug they belong to.
BY_NAME = {
    "Central African Rep.": "central-african-republic",
    "Dem. Rep. Congo": "dr-congo",
    "Eq. Guinea": "equatorial-guinea",
    "S. Sudan": "south-sudan",
    "São Tomé and Principe": "sao-tome-and-principe",
    "W. Sahara": "western-sahara",
    "eSwatini": "eswatini",
    "Cabo Verde": "cabo-verde",
    "Congo": "congo",
}


def slug_for(name):
    if name in BY_NAME:
        return BY_NAME[name]
    return name.lower().replace(" ", "-").replace("'", "")


def points(d):
    """Every coordinate pair in a path, in order. The paths here are polylines
    of absolute M/L commands and nothing else, which is why this is enough."""
    return [(float(a), float(b)) for a, b in
            re.findall(r"(-?\d+(?:\.\d+)?)[ ,]+(-?\d+(?:\.\d+)?)", d)]


def to_box(d):
    """A continent-coordinate path as a plate outline: origin, then 1000 wide."""
    ps = points(d)
    if not ps:
        return None
    xs = [p[0] for p in ps]
    ys = [p[1] for p in ps]
    w = max(xs) - min(xs)
    h = max(ys) - min(ys)
    if w <= 0 or h <= 0:
        return None
    k = BOX / w
    out = []
    for i, (x, y) in enumerate(ps):
        out.append("%s%.1f %.1f" % ("M" if i == 0 else "L",
                                    (x - min(xs)) * k, (y - min(ys)) * k))
    return {"d": "".join(out), "w": BOX, "h": round(h * k, 1)}


def paths():
    """Every country the map can draw, by slug — live, rest and island mark."""
    with open(MAP, encoding="utf-8") as fh:
        m = json.load(fh)
    out = {}
    for row in m.get("live") or []:
        if row.get("slug") and row.get("d"):
            out[row["slug"]] = row["d"]
    for row in m.get("rest") or []:
        if row.get("n") and row.get("d"):
            out.setdefault(slug_for(row["n"]), row["d"])
    return out


def promote(check=False, log=print):
    """Move every published country out of the map's background and onto it.

    map.json is generated by tools/africa_map.py from a topojson that is not in
    this repository, so it cannot simply be rebuilt: a country added to
    tourism/countries/ would keep being drawn as part of the scenery, unnamed
    and unclickable, with nothing anywhere saying so. This promotes it in place
    and uses africa_map's own anchor rule for the label, so a shape moved here
    lands where a regeneration would have put it.

    africa_map.ROSTER still wants the country adding for the day somebody does
    regenerate. That is a one-line entry and this prints the ones outstanding.
    """
    from africa_map import ROSTER, anchor
    countries = {c.slug: c for c in load_countries() if c.published}
    with open(MAP, encoding="utf-8") as fh:
        m = json.load(fh)
    on = {row.get("slug") for row in m.get("live") or []}
    on |= {row.get("slug") for row in m.get("marks") or []}

    keep, moved = [], []
    for row in m.get("rest") or []:
        slug = slug_for(row.get("n") or "")
        c = countries.get(slug)
        if not c or slug in on:
            keep.append(row)
            continue
        moved.append({"slug": slug, "name": c.name, "tag": c.tagline,
                      "href": "/" + slug, "tier": "live", "d": row["d"],
                      "at": anchor(row["d"])})
    if moved and not check:
        m["live"] = sorted((m.get("live") or []) + moved, key=lambda r: r["slug"])
        m["rest"] = keep
        with open(MAP, "w", encoding="utf-8") as fh:
            json.dump(m, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
    log("%s %d country/countries onto the map: %s"
        % ("would move" if check else "moved", len(moved),
           ", ".join(r["slug"] for r in moved) or "none"))

    listed = {v[0] for v in ROSTER.values()}
    absent = sorted(s for s in countries if s not in listed)
    if absent:
        log("  not in africa_map.ROSTER yet, so a regeneration would drop them "
            "back into the scenery: " + ", ".join(absent))
    return moved


def great_circle(a, b):
    """Kilometres between two [lon, lat] points, to the nearest kilometre."""
    lon1, lat1 = math.radians(a[0]), math.radians(a[1])
    lon2, lat2 = math.radians(b[0]), math.radians(b[1])
    dlon, dlat = lon2 - lon1, lat2 - lat1
    h = (math.sin(dlat / 2) ** 2
         + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2)
    return int(round(2 * 6371.0 * math.asin(min(1.0, math.sqrt(h)))))


def run(check=False, log=print):
    countries = load_countries()
    slugs = [c.slug for c in countries if c.published]
    have = paths()

    with open(SHAPES, encoding="utf-8") as fh:
        shapes = json.load(fh)
    with open(NEIGHBOURS, encoding="utf-8") as fh:
        nb = json.load(fh)
    centres = nb.get("centres") or {}
    borders = nb.get("borders") or {}

    problems = []

    # -- shapes ---------------------------------------------------------------
    # Only the gaps. The twenty-two written before this existed came off a finer
    # source — ninety-four points where the map carries thirty-eight — and the
    # first run of this offered to replace all twenty of them with its own
    # coarser version. Same shape, less of it. A derivation that is good enough
    # to fill an empty slot is not therefore good enough to overwrite better
    # work, and the two are easy to confuse when the diff says "20 changed".
    drawn = 0
    for slug in slugs:
        if slug in shapes:
            continue
        if slug not in have:
            # An island the map carries as a dot rather than an outline is not a
            # fault; it has no path to scale and its plate falls back to no
            # shape, which is what those two do today.
            continue
        box = to_box(have[slug])
        if not box:
            problems.append("%s: the map's path for it has no extent" % slug)
            continue
        drawn += 1
        if not check:
            shapes[slug] = box

    # -- centres --------------------------------------------------------------
    for slug in slugs:
        c = centres.get(slug)
        if not (isinstance(c, list) and len(c) == 2):
            problems.append("%s: no centre, so nothing can say how far it is" % slug)
        elif not (-30 <= c[0] <= 65 and -40 <= c[1] <= 40):
            problems.append("%s: centre %s is not in Africa" % (slug, c))

    # -- borders --------------------------------------------------------------
    known = set(slugs)
    for slug in slugs:
        for other in borders.get(slug) or []:
            if other not in known:
                problems.append("%s borders %s, which the atlas does not have"
                                % (slug, other))
            elif slug not in (borders.get(other) or []):
                problems.append("%s borders %s but %s does not border %s"
                                % (slug, other, other, slug))

    # -- km -------------------------------------------------------------------
    km = {}
    for a in slugs:
        if a not in centres:
            continue
        km[a] = {b: great_circle(centres[a], centres[b])
                 for b in slugs if b != a and b in centres}
    changed_km = km != (nb.get("km") or {})

    promote(check=check, log=log)

    if check:
        log("%d shape(s) would change, %d distance table(s) would be rebuilt"
            % (drawn, 1 if changed_km else 0))
    else:
        with open(SHAPES, "w", encoding="utf-8") as fh:
            json.dump(shapes, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
        nb["km"] = km
        with open(NEIGHBOURS, "w", encoding="utf-8") as fh:
            json.dump(nb, fh, indent=1, ensure_ascii=False)
            fh.write("\n")
        log("wrote %d outline(s) and a %dx%d distance table"
            % (len(shapes), len(km), len(km) - 1 if km else 0))

    for p in problems:
        log("  PROBLEM  " + p)
    return problems
