"""The candidate pool: everything that *could* fill a slot, before anything does.

The resolver has always thrown away the runners-up. It searched, ranked, took the
best that survived an HTTP fetch, and the other fourteen results were gone —
which is fine when the machine is choosing, and useless when a person wants to
choose. Generation makes that worse: the whole point of generating an image is
to hold it up against the stock photograph and decide.

So candidates are kept:

    tourism/candidates/index.json                 the pool, one list per slot
    tourism/candidates/<country>/<category>/*.png generated bytes

A candidate is a dict with a `source` (unsplash, pexels, openai), enough
metadata to judge it, and a `url` the contact sheet can display. It is not a
cache record and cannot be rendered by the site — promoting one to a real record
is what `pick` does, deliberately and separately.

The pool is additive and idempotent: re-collecting a slot does not duplicate a
candidate that is already there, and it never removes one, because the point of
keeping them is that you can change your mind next week.
"""

import json
import os

from .model import ROOT

DIR = os.path.join(ROOT, "tourism", "candidates")
INDEX = os.path.join(DIR, "index.json")

NOTE = ("Options for each slot, not decisions. Nothing here is served by the site "
        "until build.py pick promotes it into tourism/cache/images.json.")


def index_file():
    """Overridable so tests never write the repo's pool."""
    return os.environ.get("TOURISM_CANDIDATES_FILE") or INDEX


def category_slot(country_slug, category_id):
    """A slot on a generated /tourism/<country> page."""
    return "%s/%s" % (country_slug, category_id)


def placement_slot(placement):
    """A slot on one of the five hand-written pages.

    The page is in the key as well as the illustration id because the same
    drawing is used in more than one place, at different shapes — services.html
    crops the Foumban craft street to 4:5 and about.html to 1:1 — and those are
    two different pictures to generate, not one picture used twice.
    """
    return "site:%s:%s" % (placement["page"].rsplit(".", 1)[0], placement["id"])


class Pool:
    def __init__(self, raw=None, path=None):
        raw = raw or {}
        self.path = path or index_file()
        self.version = raw.get("version", 1)
        self.slots = raw.get("slots", {})

    # -- reads ------------------------------------------------------------------

    def all(self, slot):
        return list(self.slots.get(slot, []))

    def generated(self, slot):
        return [c for c in self.all(slot) if c.get("source") == "openai"]

    def stock(self, slot):
        return [c for c in self.all(slot) if c.get("source") != "openai"]

    def find(self, slot, candidate_id):
        for c in self.all(slot):
            if c.get("id") == candidate_id:
                return c
        return None

    def find_anywhere(self, candidate_id):
        """(slot, candidate) — picks arrive as bare ids from the contact sheet."""
        for slot, items in sorted(self.slots.items()):
            for c in items:
                if c.get("id") == candidate_id:
                    return slot, c
        return None, None

    def counts(self):
        by_source = {}
        for items in self.slots.values():
            for c in items:
                s = c.get("source") or "?"
                by_source[s] = by_source.get(s, 0) + 1
        return by_source

    # -- writes -----------------------------------------------------------------

    def add(self, slot, candidate):
        """Append unless this exact candidate is already in the slot."""
        if not candidate.get("id"):
            raise ValueError("a candidate needs an id")
        items = self.slots.setdefault(slot, [])
        for existing in items:
            if existing.get("id") == candidate["id"]:
                existing.update(candidate)
                return existing
        items.append(candidate)
        return candidate

    def remove(self, slot, candidate_id):
        items = self.slots.get(slot) or []
        before = len(items)
        self.slots[slot] = [c for c in items if c.get("id") != candidate_id]
        return before != len(self.slots[slot])

    def save(self):
        os.makedirs(os.path.dirname(self.path), exist_ok=True)
        payload = {
            "version": self.version,
            "note": NOTE,
            "slots": {k: v for k, v in sorted(self.slots.items()) if v},
        }
        with open(self.path, "w") as f:
            json.dump(payload, f, indent=2, ensure_ascii=False)
            f.write("\n")


def load(path=None):
    path = path or index_file()
    if not os.path.exists(path):
        return Pool(path=path)
    with open(path) as f:
        return Pool(json.load(f), path=path)


# ---- pulling the stock alternatives in ------------------------------------------


def from_cache_record(record):
    """The image a slot is currently using, as a candidate.

    Free — it costs no API call, because the resolver already fetched and
    verified it. Every comparison starts here: whatever is on the site now is
    the thing a generated image has to beat.
    """
    if not record or not record.get("imageUrl"):
        return None
    return {
        "source": record.get("provider") or "unknown",
        "id": "%s:%s" % (record.get("provider"), record.get("photoId")),
        "url": record.get("thumbnailUrl") or record.get("imageUrl"),
        "full": record.get("imageUrl"),
        "width": record.get("width"),
        "height": record.get("height"),
        "photographer": record.get("photographer"),
        "photographerUrl": record.get("photographerUrl"),
        "sourceUrl": record.get("sourceUrl"),
        "alt": record.get("alt"),
        "query": record.get("query"),
        "score": (record.get("relevance") or {}).get("score"),
        "reasons": (record.get("relevance") or {}).get("reasons"),
        "inUse": True,
        "createdAt": record.get("createdAt"),
    }


def from_search_candidate(cand, provider, score=None, reasons=None, query=None):
    """A runner-up from a live search — the ones the resolver used to discard."""
    return {
        "source": provider.name,
        "id": "%s:%s" % (provider.name, cand.get("photoId")),
        "url": provider.thumbnail_url(cand) or cand.get("imageUrl"),
        "full": cand.get("imageUrl"),
        "width": cand.get("width"),
        "height": cand.get("height"),
        "photographer": cand.get("photographer"),
        "photographerUrl": cand.get("photographerUrl"),
        "sourceUrl": cand.get("sourceUrl"),
        "alt": cand.get("text"),
        "query": query,
        "score": round(score, 2) if isinstance(score, (int, float)) else None,
        "reasons": reasons,
        "inUse": False,
        "createdAt": None,
    }
